template: true   # required for local templates.
valuesFilePath: ./values.yml

pipelines:
  - name: syncDeleteDR
    configuration:
      jfrogCliVersion: 2
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      #affinityGroup: together
      environmentVariables: 
        readOnly:
          JFROG_CLI_PLUGINS_SERVER: {{ .Values.jpdMain }}
          JFROG_CLI_PLUGINS_REPO: jfrog-automation
          JF_PLUGIN_REPOSYNC_INVENTORY_PATH: /tmp
    steps:
      - name: Ping
        type: utils/ping
        configuration:
          #affinityGroup: together
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          iteration: 2
          sleepBetweenIteration: 5

      - name: dryRunforDeleteRemoteRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: Ping
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete remote {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=true --inventory=false
      - name: dryRunforDeleteVirtualRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: dryRunforDeleteRemoteRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete virtual {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=true --inventory=false

      - name: approvalForDeletion
        type: Bash
        configuration:
          inputSteps:
            - name: dryRunforDeleteRemoteRepositories
            - name: dryRunforDeleteVirtualRepositories
          requiresApproval:
            timeoutSeconds: 300 # if not approved in this timeframe, the step will be cancelled
            approvers:
              - devnext-trail-user-2 # must be a valid Artifactory user
              - admin
        execution:
          onExecute:
            - echo "Received Approval. Hence performing Delete"

      - name: deleteRemoteRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: approvalForDeletion
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete remote {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=false
      - name: deleteVirtualRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: approvalForDeletion
            - name: deleteRemoteRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete virtual {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=false
