
resources:
  - name: pipelines_script_repo_2
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
        
  - name: maven_repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/frogbot-maven-hello-world
      branches:
        include: main
        
pipelines:
  - name: maven_ci_build_normal
    steps:
    - name: maven_build
      type: Bash
      configuration:
        inputResources:
          - name: maven_repo     # Trigger execution on code commit
      execution:
        onStart:
          - |
            wget https://mirrors.estointernet.in/apache/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
            tar -xvf apache-maven-3.8.6-bin.tar.gz
            mv apache-maven-3.8.6 /opt/
            M2_HOME='/opt/apache-maven-3.6.3'
            PATH="$M2_HOME/bin:$PATH"
            export PATH
            mvn -version
        onExecute:
          - echo "Hello World!"
          - cd ./dependencyState/resources/maven_repo/
          - mvn clean install
          - ls -lsa
          
