
resources:
  - name: JFrog_Pipelines_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
        
  - name: JFrog_Automation_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: main

  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/55 * * * *'     # Every 55 minutes
        
pipelines:
  - name: users_cleanup
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      integrations:
        - name: jpd_token
      environmentVariables:
        readOnly:
          dry_run:
            default: "true"
            description: This is to switch dry_run mode
            values:
              - "true"
              - "false"
          aqlname: aql_properties_match.aql
    steps:
    - name: artifacts_cleanup_step
      type: Bash
      configuration:
        integrations:
          - name: genericcreds
        inputResources:
          - name: JFrog_Automation_Repo
          - name: cron_trigger
      execution:
        onStart:
          - |
            echo "Installing Packages...."
            sudo apt-get install jq
            sudo curl -fL https://install-cli.jfrog.io | sh
            jq --version
            jf --version
            python3 --version
        onExecute:
          - jf c add psapac --url="https://psapac.jfrog.io/" --access-token="${int_jpd_token_auto_admin}" --interactive=false
          - jf c show
          - jf rt ping
          - cd ./dependencyState/resources/JFrog_Automation_Repo/cleanup_or_deletion_scripts/artifacts_cleanup_with_aql/
          - chmod +x 
          - 
        onComplete:
          - echo "The current step is running in dry_run = ${dry_run}"

