
resources:
  - name: JFrog_Pipelines_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
        
  - name: JFrog_Automation_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: main
        
pipelines:
  - name: artifacts_cleanup
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      environmentVariables:
        readOnly:
          dry_run:
            default: "true"
            description: This is to switch dry_run mode
            values:
              - "true"
              - "false"
          aqlname: aql_properties_match.aql
          JPD_TOKEN: "cmVmdGtuOjAxOjAwMDAwMDAwMDA6TFk4OUo5VGxxbmJ6bzFYNjVqa3FvNjhVRGxy"

    steps:
    - name: artifacts_cleanup_step
      type: Bash
      configuration:
        integrations:
          - name: genericcreds
        inputResources:
          - name: JFrog_Automation_Repo    
      execution:
        onStart:
          - |
            sudo apt-get install jq
            sudo curl -fL https://install-cli.jfrog.io | sh
        onExecute:
          - jq --version
          - jf --version
          - jf c add psapac --url="https://psapac.jfrog.io/" --access-token="${JPD_TOKEN}" --interactive=false
          - jf c show
          - cd ./dependencyState/resources/JFrog_Automation_Repo/cleanup_or_deletion_scripts/artifacts_cleanup_with_aql/
          - chmod +x cleanup-artifacts.sh
          - ./cleanup-artifacts.sh ${aqlname} ${dry_run}
        onComplete:
          - ls -lR
