
resources:
  - name: JFrog_Pipelines_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
        
  - name: JFrog_Automation_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: main
        
pipelines:
  - name: artifacts_cleanup
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      integrations:
        - name: jpd_token
      environmentVariables:
        readOnly:
          dry_run:
            default: "true"
            description: This is to switch dry_run mode
            values:
              - "true"
              - "false"
          aqlname: aql_properties_match.aql
    steps:
    - name: artifacts_cleanup_step
      type: Bash
      configuration:
        timeoutSeconds: 300   # 5 minutes
        integrations:
          - name: genericcreds
        inputResources:
          - name: JFrog_Automation_Repo    
      execution:
        onStart:
          - |
            sudo apt-get install jq
            jq --version
            sudo curl -fL https://install-cli.jfrog.io | sh
            jf --version
        onExecute:
          - jf c add psapac --url="https://psapac.jfrog.io/" --access-token="${int_jpd_token_auto_admin}" --interactive=false
          - jf c show
          - jf rt ping
          - cd ./dependencyState/resources/JFrog_Automation_Repo/cleanup_or_deletion_scripts/artifacts_cleanup_with_aql/
          - chmod +x cleanup-artifacts.sh
          - ./cleanup-artifacts.sh ${aqlname} ${dry_run}
        onComplete:
          - echo "The current step is running in dry_run = ${dry_run}"
