
resources:
  - name: JFrog_Pipelines_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
        
  - name: JFrog_Automation_Repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: main
        
pipelines:
  - name: artifacts_cleanup
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      environmentVariables:
        readOnly:
          aqlname: aql_properties_match.aql
          dry_run:
            default: "true"
            description: This is to switch dry_run mode
            values:
              - "true"
              - "false"

    steps:
    - name: artifacts_cleanup_step
      type: Bash
      configuration:
        integrations:
          - name: genericcreds
        inputResources:
          - name: JFrog_Automation_Repo    
      execution:
        onStart:
          - |
            sudo apt-get install jq
        onExecute:
          - echo "Hello World!"
          - ls -lsa
          - curl -fL https://install-cli.jfrog.io | sh
          - cd ./dependencyState/resources/jfrog_scripts/cleanup_or_deletion_scripts/artifacts_cleanup_with_aql/
          - chmod +x cleanup-artifacts.sh
          - ./cleanup-artifacts.sh ${aqlname} ${dry_run}
        onComplete:
          - ls -lR
