
resources:
  - name: cron_trigger_user_cleanup
    type: CronTrigger
    configuration:
      interval: '5 10 1 * 1'     # At 10:05 on day-of-month 1 and on Monday.
        
pipelines:
  - name: users_cleanup
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
      integrations:
        - name: jpd_token
      environmentVariables:
        readOnly:
          dry_run:
            default: "true"
            description: This is to switch dry_run mode
            values:
              - "true"
              - "false"
          months: 3
    steps:
    - name: users_cleanup_step
      type: Bash
      configuration:
#        integrations:
 #         - name: genericcreds
        inputResources:
          - name: JFrog_Automation_Repo
            trigger: false
 #         - name: cron_trigger_user_cleanup
      execution:
        onStart:
          - |
            echo "Installing Packages...."
            sudo apt-get install jq
            sudo curl -fL https://install-cli.jfrog.io | sh
            jq --version
            jf --version
            python3 --version
            sudo pip3 install requests
        onExecute:
          - jf c add psapac --url="https://psapac.jfrog.io/" --access-token="${int_jpd_token_auto_admin}" --interactive=false
          - jf c show
          - jf rt ping
          - echo "The current step is running in dry_run = ${dry_run}"
          - cd ./dependencyState/resources/JFrog_Automation_Repo_1/cleanup_or_deletion_scripts/users_cleanup_last_login/
          - chmod +x cleanup-users.sh
          - python3 user-list.py admin ${int_jpd_token_auto_admin}
          - ./cleanup-users.sh ${months} ${dry_run}
        onComplete:
          - echo "The current step is running in dry_run = ${dry_run}"

