
resources:
  - name: pipelines_script_repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: master
  - name: repo_check_data
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: master

pipelines:
  - name: jfrog_pipelines_demo_1
    steps:
    - name: dry_run_step
      type: Bash
      configuration:
        inputResources:
          - name: repo_check_data     # Trigger execution on code commit
      execution:
        onExecute:
          - echo "Hello World!"
          - ls
          - ls workspace/
          - jf c s
          - find . -type f -name "*.sh"
          - chmod +x getRepoList.sh
          - ./getRepoList.sh https://ramkannan.jfrog.io local admin cmVmdGtuOjAxOjAwMDAwMDAwMDA6Q3NGVFpVM1d4a2d2UDRVaVJvWnA1RVlPVFVP
