
resources:
  - name: pipelines_script_repo
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog-pipelines-sample-1
      branches:
        include: main
  - name: repo_check_data
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: main

pipelines:
  - name: jfrog_pipelines_demo_1
    steps:
    - name: dry_run_step
      type: Bash
      configuration:
        inputResources:
          - name: repo_check_data     # Trigger execution on code commit
      execution:
        onExecute:
          - echo "Hello World!"
          - cd ./dependencyState/resources/repo_check_data/repos_scripts/
          - curl -fL https://install-cli.jfrog.io | sh
          - jf c show
          - jf --version
          - ls -lsa
          - sudo apt-get update -y
          - sudo apt-get install jq -y
          - ./getRepoList.sh https://ramkannan.jfrog.io local admin cmVmdGtuOjAxOjAwMDAwMDAwMDA6Q3NGVFpVM1d4a2d2UDRVaVJvWnA1RVlPVFVP
