
resources:
  - name: repo_check_data
    type: GitRepo
    configuration:
      gitProvider: github_ram
      path: ramkannan-s/jfrog_scripts
      branches:
        include: master

pipelines:
  - name: jfrog_pipelines_demo_1
    steps:
    - name: dry_run_step
      type: Bash
      configuration:
        inputResources:
          - name: repo_check_data     # Trigger execution on code commit
      execution:
        onExecute:
          - echo "Hello World!"
